In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/diabetes_dataset.csv")

In [3]:
df.columns

Index(['year', 'gender', 'age', 'location', 'race:AfricanAmerican',
       'race:Asian', 'race:Caucasian', 'race:Hispanic', 'race:Other',
       'hypertension', 'heart_disease', 'smoking_history', 'bmi',
       'hbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')

In [4]:
print("Dataset com:")
print(f"Linhas: {df.shape[0]}")
print(f"Colunas: {df.shape[1]}")

Dataset com:
Linhas: 100000
Colunas: 16

In [5]:
df.head()

,year,gender,age,location,race:AfricanAmerican,race:Asian,race:Caucasian,race:Hispanic,race:Other,hypertension,heart_disease,smoking_history,bmi,hbA1c_level,blood_glucose_level,diabetes
0,2020,Female,32.0,Alabama,0,0,0,0,1,0,0,never,27.32,5.0,100,0
1,2015,Female,29.0,Alabama,0,1,0,0,0,0,0,never,19.95,5.0,90,0
2,2015,Male,18.0,Alabama,0,0,0,0,1,0,0,never,23.76,4.8,160,0
3,2015,Male,41.0,Alabama,0,0,1,0,0,0,0,never,27.32,4.0,159,0
4,2016,Female,52.0,Alabama,1,0,0,0,0,0,0,never,23.75,6.5,90,0

In [6]:
df.tail()

,year,gender,age,location,race:AfricanAmerican,race:Asian,race:Caucasian,race:Hispanic,race:Other,hypertension,heart_disease,smoking_history,bmi,hbA1c_level,blood_glucose_level,diabetes
99995,2018,Female,33.0,Wyoming,0,0,0,0,1,0,0,never,21.21,6.5,90,0
99996,2016,Female,80.0,Wyoming,0,1,0,0,0,0,0,No Info,36.66,5.7,100,0
99997,2018,Male,46.0,Wyoming,0,1,0,0,0,0,0,ever,36.12,6.2,158,0
99998,2018,Female,51.0,Wyoming,1,0,0,0,0,0,0,not current,29.29,6.0,155,0
99999,2016,Male,13.0,Wyoming,0,0,0,1,0,0,0,No Info,17.16,5.0,90,0

In [7]:
df.sample(5)

,year,gender,age,location,race:AfricanAmerican,race:Asian,race:Caucasian,race:Hispanic,race:Other,hypertension,heart_disease,smoking_history,bmi,hbA1c_level,blood_glucose_level,diabetes
7292,2019,Female,6.0,Arkansas,0,0,1,0,0,0,0,No Info,13.99,4.0,80,0
60918,2019,Male,57.0,New Hampshire,0,0,0,0,1,1,0,never,33.92,4.8,200,0
39921,2016,Female,42.0,Maine,1,0,0,0,0,0,0,current,27.32,6.2,140,0
82067,2019,Female,43.0,Rhode Island,0,0,0,1,0,0,1,No Info,27.32,6.1,126,0
96618,2019,Male,77.0,Virginia,0,0,0,0,1,0,0,former,27.32,4.8,80,0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   year                  100000 non-null  int64
 1   gender                100000 non-null  object
 2   age                   100000 non-null  float64
 3   location              100000 non-null  object
 4   race:AfricanAmerican  100000 non-null  int64
 5   race:Asian            100000 non-null  int64
 6   race:Caucasian        100000 non-null  int64
 7   race:Hispanic         100000 non-null  int64
 8   race:Other            100000 non-null  int64
 9   hypertension          100000 non-null  int64
 10  heart_disease         100000 non-null  int64
 11  smoking_history       100000 non-null  object
 12  bmi                   100000 non-null  float64
 13  hbA1c_level           100000 non-null  float64
 14  blood_glucose_level   100000 non-null  int64
 15  diabetes              100000 non-null  int64
dtypes: float64(3), int64(10), object(3)
memory usage: 12.2+ MB

In [9]:
df.isnull().sum() / len(df)

year                    0.0
gender                  0.0
age                     0.0
location                0.0
race:AfricanAmerican    0.0
race:Asian              0.0
race:Caucasian          0.0
race:Hispanic           0.0
race:Other              0.0
hypertension            0.0
heart_disease           0.0
smoking_history         0.0
bmi                     0.0
hbA1c_level             0.0
blood_glucose_level     0.0
diabetes                0.0
dtype: float64

In [10]:
pd.DataFrame(df.isnull().sum()).T.style.background_gradient(cmap='coolwarm')

In [11]:
df.describe(percentiles=[0, .25, .50, .75]).T.style.background_gradient(cmap='coolwarm')

In [12]:
colunas_cat = df.select_dtypes(include=['object']).columns.to_list()
for col in df[colunas_cat]:
    print(f"\nColuna: {col}\n{df[col].value_counts()}")
    print(f"\nColuna: {col}\n{df[col].value_counts(normalize=True)}")

Coluna: gender
gender
Female    58552
Male      41430
Other        18
Name: count, dtype: int64

Coluna: gender
gender
Female    0.58552
Male      0.41430
Other     0.00018
Name: proportion, dtype: float64

Coluna: location
location
Iowa                    2038
Nebraska                2038
Kentucky                2038
Hawaii                  2038
Florida                 2037
Minnesota               2037
New Jersey              2037
Arkansas                2037
Delaware                2036
Kansas                  2036
Michigan                2036
Massachusetts           2036
Maine                   2036
District of Columbia    2036
Louisiana               2036
Georgia                 2036
Oregon                  2036
Pennsylvania            2036
Alabama                 2036
Illinois                2036
Rhode Island            2035
Colorado                2035
Maryland                2035
New York                2035
Connecticut             2035
Mississippi             2035
Missouri                2035
Alaska                  2035
North Carolina          2035
New Hampshire           2035
North Dakota            2035
South Dakota            2033
Montana                 2033
New Mexico              2033
Idaho                   1988
South Carolina          1987
Indiana                 1987
Ohio                    1986
Oklahoma                1986
Nevada                  1986
Arizona                 1986
California              1986
Tennessee               1574
United States           1401
Washington              1363
Utah                    1359
Virginia                1350
Vermont                 1338
Texas                   1337
Puerto Rico             1295
Guam                    1204
West Virginia           1132
Virgin Islands           763
Wisconsin                388
Wyoming                  388
Name: count, dtype: int64

Coluna: location
location
Iowa                    0.02038
Nebraska                0.02038
Kentucky                0.02038
Hawaii                  0.02038
Florida                 0.02037
Minnesota               0.02037
New Jersey              0.02037
Arkansas                0.02037
Delaware                0.02036
Kansas                  0.02036
Michigan                0.02036
Massachusetts           0.02036
Maine                   0.02036
District of Columbia    0.02036
Louisiana               0.02036
Georgia                 0.02036
Oregon                  0.02036
Pennsylvania            0.02036
Alabama                 0.02036
Illinois                0.02036
Rhode Island            0.02035
Colorado                0.02035
Maryland                0.02035
New York                0.02035
Connecticut             0.02035
Mississippi             0.02035
Missouri                0.02035
Alaska                  0.02035
North Carolina          0.02035
New Hampshire           0.02035
North Dakota            0.02035
South Dakota            0.02033
Montana                 0.02033
New Mexico              0.02033
Idaho                   0.01988
South Carolina          0.01987
Indiana                 0.01987
Ohio                    0.01986
Oklahoma                0.01986
Nevada                  0.01986
Arizona                 0.01986
California              0.01986
Tennessee               0.01574
United States           0.01401
Washington              0.01363
Utah                    0.01359
Virginia                0.01350
Vermont                 0.01338
Texas                   0.01337
Puerto Rico             0.01295
Guam                    0.01204
West Virginia           0.01132
Virgin Islands          0.00763
Wisconsin               0.00388
Wyoming                 0.00388
Name: proportion, dtype: float64

Coluna: smoking_history
smoking_history
No Info        35816
never          35095
former          9352
current         9286
not current     6447
ever            4004
Name: count, dtype: int64

Coluna: smoking_history
smoking_history
No Info        0.35816
never          0.35095
former         0.09352
current        0.09286
not current    0.06447
ever           0.04004
Name: proportion, dtype: float64

In [13]:
def contagem_outliers(df):
    colunas_num = df.select_dtypes(include=['int64', 'float64']).columns.to_list()
    outliers_count = {}
    for col in colunas_num:
        z_scores = np.abs((df[col] - df[col].mean()) / df[col].std())
        outliers = df[z_scores > 3]
        outliers_count[col] = len(outliers)
    return outliers_count

outliers_count = contagem_outliers(df)
print("Contagem de outliers utilizando Z-Score:")
for col, count in outliers_count.items():
    print(f"{col}: {count}")

Contagem de outliers utilizando Z-Score:
year: 0
age: 0
race:AfricanAmerican: 0
race:Asian: 0
race:Caucasian: 0
race:Hispanic: 0
race:Other: 0
hypertension: 7485
heart_disease: 3942
bmi: 1294
hbA1c_level: 1315
blood_glucose_level: 1403
diabetes: 8500

In [14]:
colunas_num = [col for col in df.columns if df[col].dtype in ['int64', 'float64']]

print("\nQuantidade de outliers em cada coluna numérica utilizando Quartil:")
for col in colunas_num:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    outliers = df[(df[col] < (Q1 - 1.5 * IQR)) | (df[col] > (Q3 + 1.5 * IQR))]
    print(f"{col}: {outliers.shape[0]}")

Quantidade de outliers em cada coluna numérica utilizando Quartil:
year: 20255
age: 0
race:AfricanAmerican: 20223
race:Asian: 20015
race:Caucasian: 19876
race:Hispanic: 19888
race:Other: 19998
hypertension: 7485
heart_disease: 3942
bmi: 7086
hbA1c_level: 1315
blood_glucose_level: 2038
diabetes: 8500

In [15]:
df_transformado = pd.read_csv("../data/dados_transformados.csv")

In [16]:
def correlacao_cor(val):
    if val >= 0.6 and val < 0.99999 or val <= -0.6 and val > -0.99999:
      color = 'red'
    elif val < 0.6 and val >= 0.3 or val > -0.6 and val <= -0.3:
      color = 'blue'
    elif val == 1:
       color = 'green'
    else:
        color = 'black'
    return 'color: %s' % color  

df_transformado.corr().style.applymap(correlacao_cor)

C:\Users\caioc\AppData\Local\Temp\ipykernel_17900\4140880459.py:12: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  df_transformado.corr().style.applymap(correlacao_cor)

In [17]:
df_transformado.corr()['diabetes'].sort_values(key=abs, ascending=False)

diabetes                       1.000000
blood_glucose_level            0.419558
hbA1c_level                    0.400660
age                            0.258008
bmi                            0.214357
hypertension                   0.197823
heart_disease                  0.171727
smoking_history_former         0.097917
gender                         0.037411
smoking_history_never          0.027267
smoking_history_ever           0.024080
smoking_history_not current    0.020734
smoking_history_current        0.019606
race:Other                    -0.005095
race:AfricanAmerican           0.004378
race:Asian                     0.003739
race:Caucasian                -0.001749
race:Hispanic                 -0.001301
Name: diabetes, dtype: float64